//! A migration that has shipped is immutable, and this is what enforces it.
//!
//! sqlx records a checksum of each migration's **file bytes** the first time it
//! runs, re-hashes on every later boot, and refuses to open the database if any
//! of them differs. Comments and whitespace count. So an edit to a released
//! migration is not a cosmetic change: it is an outage on every installation
//! that already applied it, and one that only shows up at somebody else's
//! startup, days after the commit that caused it.
//!
//! That is not hypothetical. The rename to croit AIplane swept a documentation
//! path (`docs/rag.md` → `docs/fileshare-rag.md`) through the tree, and one of
//! the hits was a comment inside `0013_rag.sql`, a migration from the initial
//! public release. Every existing deployment stopped booting with "migration 13
//! was previously applied but has been modified". `migrations/README.md` had
//! said not to do this since before the project was public; a rule that only
//! exists in prose is a rule a `sed` does not read.
//!
//! So the checksums are pinned in `migration-checksums.txt` and compared here,
//! using sqlx's own hash — the same number production compares against. Adding
//! a migration means appending one line. Changing an existing line is the thing
//! this test exists to stop.

use std::collections::BTreeMap;

/// Committed, one `<version> <checksum>` per line. Generated by the failure
/// message below rather than by hand.
const FROZEN: &str = include_str!("migration-checksums.txt");

fn frozen() -> BTreeMap<i64, String> {
    FROZEN
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (version, checksum) = line
                .split_once(char::is_whitespace)
                .unwrap_or_else(|| panic!("malformed line in migration-checksums.txt: {line:?}"));
            (
                version.parse().unwrap_or_else(|err| {
                    panic!("migration-checksums.txt: {version:?} is not a version: {err}")
                }),
                checksum.trim().to_owned(),
            )
        })
        .collect()
}

fn on_disk() -> BTreeMap<i64, String> {
    sqlx::migrate!("./migrations")
        .migrations
        .iter()
        .map(|migration| {
            let checksum = migration.checksum.iter().fold(String::new(), |mut acc, b| {
                use std::fmt::Write;
                let _ = write!(acc, "{b:02x}");
                acc
            });
            (migration.version, checksum)
        })
        .collect()
}

#[test]
fn no_released_migration_has_been_modified() {
    let frozen = frozen();
    let on_disk = on_disk();

    let modified: Vec<_> = on_disk
        .iter()
        .filter_map(|(version, checksum)| {
            frozen
                .get(version)
                .filter(|pinned| *pinned != checksum)
                .map(|pinned| format!("  {version}: pinned {pinned}, on disk {checksum}"))
        })
        .collect();

    assert!(
        modified.is_empty(),
        "these migrations have already run in production and their bytes changed:\n{}\n\n\
         Every installation that applied them will refuse to start with \"migration N was \
         previously applied but has been modified\". Put the change in a NEW numbered \
         migration and restore these files exactly — including comments and whitespace. \
         See crates/aiplane-core/migrations/README.md.",
        modified.join("\n")
    );
}

#[test]
fn every_migration_is_pinned() {
    let frozen = frozen();
    let unpinned: Vec<_> = on_disk()
        .iter()
        .filter(|(version, _)| !frozen.contains_key(version))
        .map(|(version, checksum)| format!("{version} {checksum}"))
        .collect();

    assert!(
        unpinned.is_empty(),
        "new migrations are not pinned yet. Append these lines to \
         crates/aiplane-core/tests/migration-checksums.txt, and only ever append:\n{}",
        unpinned.join("\n")
    );
}

#[test]
fn nothing_pinned_has_disappeared() {
    let on_disk = on_disk();
    let vanished: Vec<_> = frozen()
        .keys()
        .filter(|version| !on_disk.contains_key(version))
        .map(i64::to_string)
        .collect();

    assert!(
        vanished.is_empty(),
        "migrations {} are pinned but no longer on disk. Deleting a migration that has run \
         leaves every existing database with a row sqlx cannot match, so it is the same \
         outage as editing one.",
        vanished.join(", ")
    );
}
